apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"labels":{"application":"stakaterfe","template":"openjdk18-web-basic-s2i","xpaas":"1.4.14"},"name":"stakaterfe","namespace":"exp-gcas7-test"},"spec":{"replicas":1,"selector":{"deploymentConfig":"stakaterfe"},"strategy":{"resources":{"limits":{"cpu":1,"memory":"2Gi"},"requests":{"cpu":1,"memory":"2Gi"}},"rollingParams":{"intervalSeconds":1,"maxSurge":"20%","maxUnavailable":0,"timeoutSeconds":600,"updatePeriodSeconds":1},"type":"Rolling"},"template":{"metadata":{"labels":{"application":"stakaterfe","deploymentConfig":"stakaterfe"},"name":"stakaterfe"},"spec":{"containers":[{"env":[{"name":"JAVA_OPTIONS","value":""},{"name":"HTTPS_PROXY","value":""},{"name":"https_proxy","value":""},{"name":"HTTP_PROXY","value":""},{"name":"http_proxy","value":""},{"name":"GC_MAX_METASPACE_SIZE","value":"300"}],"imagePullPolicy":"Always","name":"stakaterfe","ports":[{"containerPort":8778,"name":"jolokia","protocol":"TCP"},{"containerPort":8080,"name":"http","protocol":"TCP"},{"containerPort":8443,"name":"https","protocol":"TCP"}],"resources":{"limits":{"cpu":0.5,"memory":"2Gi"},"requests":{"cpu":0.5,"memory":"2Gi"}}}],"terminationGracePeriodSeconds":75}},"triggers":[{"imageChangeParams":{"automatic":false,"containerNames":["stakaterfe"],"from":{"kind":"ImageStreamTag","name":"stakaterfe:latest"}},"type":"ImageChange"}]}}
  creationTimestamp: '2021-06-12T07:47:07Z'
  generation: 8
  labels:
    application: stakaterfe
    template: openjdk18-web-basic-s2i
    xpaas: 1.4.14
  name: stakaterfe
  namespace: exp-gcas7-test
  resourceVersion: '1550902725'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/exp-gcas7-test/deploymentconfigs/stakaterfe
  uid: 6329140c-cb52-11eb-8754-0050569a2603
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentConfig: stakaterfe
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: '1'
        memory: 2Gi
    rollingParams:
      intervalSeconds: 1
      maxSurge: 20%
      maxUnavailable: 0
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: stakaterfe
        deploymentConfig: stakaterfe
      name: stakaterfe
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
            - name: HTTPS_PROXY
            - name: https_proxy
            - name: HTTP_PROXY
            - name: http_proxy
            - name: GC_MAX_METASPACE_SIZE
              value: '300'
          image: >-
            docker-registry.default.svc:5000/exp-gcas7-test/stakaterfe@sha256:83682f3786807a5d0b415e82583c5147735511da152c97df3f4b103f97b2098e
          imagePullPolicy: Always
          name: stakaterfe
          ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 75
  test: false
  triggers:
    - imageChangeParams:
        containerNames:
          - stakaterfe
        from:
          kind: ImageStreamTag
          name: 'stakaterfe:latest'
          namespace: exp-gcas7-test
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/exp-gcas7-test/stakaterfe@sha256:83682f3786807a5d0b415e82583c5147735511da152c97df3f4b103f97b2098e
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2021-06-12T08:42:05Z'
      lastUpdateTime: '2021-06-12T08:42:05Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2021-06-12T08:42:06Z'
      lastUpdateTime: '2021-06-12T08:42:08Z'
      message: replication controller "stakaterfe-2" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: Manual
    message: manual change
  latestVersion: 2
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
